In [1]:
# AC 欄位 = 中風日期 
# AD 欄位 = 心肌哽塞日期
    
# NaN欄位直接移除
# 值為1的會再去確認

# IF 沒有中風 , time = 20230616 - 第一張眼底鏡日期
# IF 中風          , time = 發病的日期-第一張眼底鏡日期

In [2]:
import pandas as pd
import os

In [3]:
outcomefile = pd.DataFrame(pd.read_excel('/home/john/network/RETFound/data/202301-0616共照網個案_Wei_0227.xlsx'))

In [5]:
outcomefile.to_csv('/john/network/RETFound/data/csv/0227.csv',index=False)

In [6]:
dataset = pd.read_csv("/john/network/RETFound/data/csv/0227.csv.csv")
Image_data =  "/home/john/network/RETFound/data/ROI/"

In [7]:
dataset

,病歷號,年齡,性別,fundoscope(共做過幾次),1st fundo (date),2nd fundo (date),3rd fundo (date),4rd fundo (date),5rd fundo (date),6rd fundo (date),...,運動種類,運動頻率分/次,運動頻率次/週,衛教檢驗日期,飲食,藥物認識,運動的目的及注意事項,生病時的照顧,自我監測,指導注射技巧
0,4314535,64,1,14.0,20080415,20090210.0,20100205.0,20110419.0,20120424.0,20130618.0,...,NaN,NaN,NaN,2023/03/03,NaN,NaN,NaN,NaN,NaN,NaN
1,4069957,69,1,8.0,20051215,20150506.0,20170202.0,20171225.0,20190116.0,20200422.0,...,NaN,NaN,NaN,2023/04/12,NaN,NaN,NaN,NaN,NaN,NaN
2,4386971,71,2,3.0,20200214,20210414.0,20220801.0,NaN,NaN,NaN,...,NaN,NaN,NaN,2023/01/17,NaN,NaN,NaN,NaN,NaN,NaN
3,4845785,53,1,3.0,20200811,20211202.0,20230119.0,NaN,NaN,NaN,...,NaN,NaN,NaN,2023/01/18,NaN,NaN,NaN,NaN,NaN,NaN
4,4132852,60,2,4.0,20180117,20181002.0,20200226.0,20221028.0,NaN,NaN,...,NaN,NaN,NaN,2023/05/29,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,4241840,69,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2023/06/06,NaN,NaN,1.0,NaN,NaN,NaN
1303,1795454,62,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,2685764,64,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1305,3807636,56,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1306,2231493,72,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2023/06/14,NaN,NaN,NaN,NaN,NaN,NaN

抽菸NaN補0

In [8]:
smoke = dataset['抽菸']
smoke.fillna(0,inplace=True)

smoke = smoke.replace(["N","Y"],[0,1],inplace=True)

身高、體重、BMI中位數計算 & 補值

In [9]:
height = dataset['身高']
weight = dataset['體重']
BMI = dataset['BMI']

height_value = height.median()    # 160
weight_value = weight.median()  # 66.4
BMI_value = BMI.median()               # 25.78

height.fillna(height_value,inplace=True)
weight.fillna(weight_value,inplace=True)
BMI.fillna(BMI_value,inplace=True)

高血壓、血脂異常 NaN 補0

In [10]:
Hypertension = dataset['高血壓']
Dyslipidemia = dataset['血脂異常']

Hypertension.fillna(0,inplace=True)
Dyslipidemia.fillna(0,inplace=True)

In [11]:
keep = ['病歷號','年齡','抽菸','身高','體重','BMI','MI   (date)','stroke   (date)','高血壓','血脂異常']

dataset = dataset[keep]

In [12]:
dataset

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常
0,4314535,64,0,163.6,67.0,25.03,0,0,0.0,1.0
1,4069957,69,0,171.0,73.0,24.96,0,0,0.0,0.0
2,4386971,71,0,147.8,77.8,35.61,0,0,0.0,0.0
3,4845785,53,0,170.8,80.3,27.53,0,0,0.0,0.0
4,4132852,60,0,152.0,51.0,22.07,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
1302,4241840,69,0,161.3,53.9,20.72,NaN,NaN,0.0,1.0
1303,1795454,62,0,163.0,67.0,25.22,NaN,NaN,1.0,1.0
1304,2685764,64,0,155.7,85.1,35.10,NaN,NaN,0.0,0.0
1305,3807636,56,0,160.0,66.4,25.78,NaN,NaN,0.0,0.0
1306,2231493,72,0,152.9,66.8,28.57,NaN,NaN,0.0,1.0

病歷號替換成檔名

In [13]:
file_list = os.listdir(Image_data)
new_dataframe = pd.DataFrame(columns=dataset.columns)

for filename in file_list:
    start = 0

    for i in range(start,len(filename)):
        if filename[i] == '-':
            found = True
            break
    
    if found:
        match = False

        for j in range(0, len(dataset['病歷號'])):
            if filename[start:i] == str(dataset['病歷號'][j]):
                new_row = dataset.iloc[j]
                new_dataframe = new_dataframe.append(new_row,ignore_index = True)
                match = True
                
        if not match:
                    print(f"Not found : {filename[start:i]}")

In [14]:
new_dataframe

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常
0,4385815,70,0,149.0,71.0,31.98,0,0,1.0,1.0
1,7093981,51,0,155.0,75.0,31.22,0,0,1.0,1.0
2,4940688,60,0,167.7,93.3,33.18,0,0,0.0,0.0
3,2310298,60,0,162.1,69.5,26.45,0,0,0.0,0.0
4,4540756,72,0,166.2,78.7,28.49,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
8163,4092882,68,0,150.9,55.8,24.51,0,0,0.0,1.0
8164,4161150,60,1,173.0,64.0,21.38,0,0,0.0,1.0
8165,4073719,79,0,158.4,64.0,25.51,0,0,0.0,1.0
8166,7096147,51,0,164.7,61.3,22.60,0,0,0.0,0.0
8167,7064104,64,0,146.3,61.5,28.73,0,0,0.0,0.0

In [15]:
# Loading Fundus Images
ImageFilePath = '/home/john/network/RETFound/data/ROI'
ImageFileNames = [filename for filename in os.listdir(ImageFilePath)]

new_dataframe['病歷號']  = ImageFileNames

In [16]:
new_dataframe

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常
0,4385815-02-L-20170802.jpg,70,0,149.0,71.0,31.98,0,0,1.0,1.0
1,7093981-05-L-20200804.jpg,51,0,155.0,75.0,31.22,0,0,1.0,1.0
2,4940688-05-R-20230201.jpg,60,0,167.7,93.3,33.18,0,0,0.0,0.0
3,2310298-05-L-20220708.jpg,60,0,162.1,69.5,26.45,0,0,0.0,0.0
4,4540756-03-R-20211102.jpg,72,0,166.2,78.7,28.49,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
8163,4092882-01-R-20190103.jpg,68,0,150.9,55.8,24.51,0,0,0.0,1.0
8164,4161150-04-L-20200131.jpg,60,1,173.0,64.0,21.38,0,0,0.0,1.0
8165,4073719-08-R-20230710.jpg,79,0,158.4,64.0,25.51,0,0,0.0,1.0
8166,7096147-02-R-20220816.jpg,51,0,164.7,61.3,22.60,0,0,0.0,0.0
8167,7064104-06-L-20230508.jpg,64,0,146.3,61.5,28.73,0,0,0.0,0.0

remove MI (date) NaN & stroke (data) NaN

In [17]:
removeMI_NaN = new_dataframe.dropna(axis=0, subset=['MI   (date)'])
removeMI_NaN = removeMI_NaN.reset_index(drop=True)

In [18]:
removeMI_NaN

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常
0,4385815-02-L-20170802.jpg,70,0,149.0,71.0,31.98,0,0,1.0,1.0
1,7093981-05-L-20200804.jpg,51,0,155.0,75.0,31.22,0,0,1.0,1.0
2,4940688-05-R-20230201.jpg,60,0,167.7,93.3,33.18,0,0,0.0,0.0
3,2310298-05-L-20220708.jpg,60,0,162.1,69.5,26.45,0,0,0.0,0.0
4,4540756-03-R-20211102.jpg,72,0,166.2,78.7,28.49,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
8103,4092882-01-R-20190103.jpg,68,0,150.9,55.8,24.51,0,0,0.0,1.0
8104,4161150-04-L-20200131.jpg,60,1,173.0,64.0,21.38,0,0,0.0,1.0
8105,4073719-08-R-20230710.jpg,79,0,158.4,64.0,25.51,0,0,0.0,1.0
8106,7096147-02-R-20220816.jpg,51,0,164.7,61.3,22.60,0,0,0.0,0.0
8107,7064104-06-L-20230508.jpg,64,0,146.3,61.5,28.73,0,0,0.0,0.0

In [19]:
removeStroke_NaN = new_dataframe.dropna(axis=0, subset=['stroke   (date)'])
removeStroke_NaN = removeStroke_NaN.reset_index(drop=True)

In [20]:
removeStroke_NaN

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常
0,4385815-02-L-20170802.jpg,70,0,149.0,71.0,31.98,0,0,1.0,1.0
1,7093981-05-L-20200804.jpg,51,0,155.0,75.0,31.22,0,0,1.0,1.0
2,4940688-05-R-20230201.jpg,60,0,167.7,93.3,33.18,0,0,0.0,0.0
3,2310298-05-L-20220708.jpg,60,0,162.1,69.5,26.45,0,0,0.0,0.0
4,4540756-03-R-20211102.jpg,72,0,166.2,78.7,28.49,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
8129,4092882-01-R-20190103.jpg,68,0,150.9,55.8,24.51,0,0,0.0,1.0
8130,4161150-04-L-20200131.jpg,60,1,173.0,64.0,21.38,0,0,0.0,1.0
8131,4073719-08-R-20230710.jpg,79,0,158.4,64.0,25.51,0,0,0.0,1.0
8132,7096147-02-R-20220816.jpg,51,0,164.7,61.3,22.60,0,0,0.0,0.0
8133,7064104-06-L-20230508.jpg,64,0,146.3,61.5,28.73,0,0,0.0,0.0

真實年齡

In [21]:
removeStroke_NaN["真實年齡"] = ""

for i in range(len(removeStroke_NaN.病歷號)):
    removeStroke_NaN["真實年齡"][i] = int(removeStroke_NaN["年齡"][i]) - (2023 - int(removeStroke_NaN["病歷號"][i][-12:-8]))

/home/john/anaconda3/envs/retfound/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [22]:
removeStroke_NaN

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常,真實年齡
0,4385815-02-L-20170802.jpg,70,0,149.0,71.0,31.98,0,0,1.0,1.0,64
1,7093981-05-L-20200804.jpg,51,0,155.0,75.0,31.22,0,0,1.0,1.0,48
2,4940688-05-R-20230201.jpg,60,0,167.7,93.3,33.18,0,0,0.0,0.0,60
3,2310298-05-L-20220708.jpg,60,0,162.1,69.5,26.45,0,0,0.0,0.0,59
4,4540756-03-R-20211102.jpg,72,0,166.2,78.7,28.49,0,0,0.0,1.0,70
...,...,...,...,...,...,...,...,...,...,...,...
8129,4092882-01-R-20190103.jpg,68,0,150.9,55.8,24.51,0,0,0.0,1.0,64
8130,4161150-04-L-20200131.jpg,60,1,173.0,64.0,21.38,0,0,0.0,1.0,57
8131,4073719-08-R-20230710.jpg,79,0,158.4,64.0,25.51,0,0,0.0,1.0,79
8132,7096147-02-R-20220816.jpg,51,0,164.7,61.3,22.60,0,0,0.0,0.0,50
8133,7064104-06-L-20230508.jpg,64,0,146.3,61.5,28.73,0,0,0.0,0.0,64

年齡 -> 預測年齡

In [23]:
import joblib
import numpy as np
import pandas as pd

from skimage.io import imread 
from skimage.transform import resize

In [24]:
loaded_model = joblib.load('/home/john/network/RETFound/RETFound_MAE-main/Fundus_deepsurv/Regression/xgb_model.pkl')

In [25]:
Image_path_predict = "/home/john/network/RETFound/data/ROI/"

In [26]:
def extract_features_predict(fundusimage):
    fundusimage = Image_path_predict + fundusimage

    image = imread(fundusimage)
    image = resize(image, (224, 224)) 

    feature_vector = image.flatten()
    
    return feature_vector

In [27]:
df = pd.DataFrame(columns=['File', 'Predicted_Result'])

for fundusimage in os.listdir(Image_path_predict):
    feature = extract_features_predict(fundusimage)
    prediction = loaded_model.predict([feature])[0]
    
    df = df.append({'File': fundusimage, 'Predicted_Result': prediction}, ignore_index=True)

In [28]:
df

                           File  Predicted_Result
0     4385815-02-L-20170802.jpg         57.276569
1     7093981-05-L-20200804.jpg         47.467751
2     4940688-05-R-20230201.jpg         57.765377
3     2310298-05-L-20220708.jpg         63.910080
4     4540756-03-R-20211102.jpg         55.230278
...                         ...               ...
8163  4092882-01-R-20190103.jpg         61.213776
8164  4161150-04-L-20200131.jpg         56.386856
8165  4073719-08-R-20230710.jpg         69.473015
8166  7096147-02-R-20220816.jpg         45.289669
8167  7064104-06-L-20230508.jpg         62.306839

[8168 rows x 2 columns]

In [29]:
df = df.rename(columns={"File":"病歷號","Predicted_Result":"預測結果"})

In [30]:
df

                            病歷號       預測結果
0     4385815-02-L-20170802.jpg  57.276569
1     7093981-05-L-20200804.jpg  47.467751
2     4940688-05-R-20230201.jpg  57.765377
3     2310298-05-L-20220708.jpg  63.910080
4     4540756-03-R-20211102.jpg  55.230278
...                         ...        ...
8163  4092882-01-R-20190103.jpg  61.213776
8164  4161150-04-L-20200131.jpg  56.386856
8165  4073719-08-R-20230710.jpg  69.473015
8166  7096147-02-R-20220816.jpg  45.289669
8167  7064104-06-L-20230508.jpg  62.306839

[8168 rows x 2 columns]

In [31]:
merged_df = pd.merge(removeStroke_NaN, df, on="病歷號")

In [32]:
merged_df

,病歷號,年齡,抽菸,身高,體重,BMI,MI (date),stroke (date),高血壓,血脂異常,真實年齡,預測結果
0,4385815-02-L-20170802.jpg,70,0,149.0,71.0,31.98,0,0,1.0,1.0,64,57.276569
1,7093981-05-L-20200804.jpg,51,0,155.0,75.0,31.22,0,0,1.0,1.0,48,47.467751
2,4940688-05-R-20230201.jpg,60,0,167.7,93.3,33.18,0,0,0.0,0.0,60,57.765377
3,2310298-05-L-20220708.jpg,60,0,162.1,69.5,26.45,0,0,0.0,0.0,59,63.910080
4,4540756-03-R-20211102.jpg,72,0,166.2,78.7,28.49,0,0,0.0,1.0,70,55.230278
...,...,...,...,...,...,...,...,...,...,...,...,...
8129,4092882-01-R-20190103.jpg,68,0,150.9,55.8,24.51,0,0,0.0,1.0,64,61.213776
8130,4161150-04-L-20200131.jpg,60,1,173.0,64.0,21.38,0,0,0.0,1.0,57,56.386856
8131,4073719-08-R-20230710.jpg,79,0,158.4,64.0,25.51,0,0,0.0,1.0,79,69.473015
8132,7096147-02-R-20220816.jpg,51,0,164.7,61.3,22.60,0,0,0.0,0.0,50,45.289669
8133,7064104-06-L-20230508.jpg,64,0,146.3,61.5,28.73,0,0,0.0,0.0,64,62.306839

Event = stroke

In [34]:
merged_df = merged_df.rename(columns={"MI   (date)":"MI","stroke   (date)":"Event"})

In [ ]:
merged_df = merged_df.drop(columns=['MI','年齡'])

In [39]:
merged_df

,病歷號,抽菸,身高,體重,BMI,Event,高血壓,血脂異常,真實年齡,預測結果
0,4385815-02-L-20170802.jpg,0,149.0,71.0,31.98,0,1.0,1.0,64,57.276569
1,7093981-05-L-20200804.jpg,0,155.0,75.0,31.22,0,1.0,1.0,48,47.467751
2,4940688-05-R-20230201.jpg,0,167.7,93.3,33.18,0,0.0,0.0,60,57.765377
3,2310298-05-L-20220708.jpg,0,162.1,69.5,26.45,0,0.0,0.0,59,63.910080
4,4540756-03-R-20211102.jpg,0,166.2,78.7,28.49,0,0.0,1.0,70,55.230278
...,...,...,...,...,...,...,...,...,...,...
8129,4092882-01-R-20190103.jpg,0,150.9,55.8,24.51,0,0.0,1.0,64,61.213776
8130,4161150-04-L-20200131.jpg,1,173.0,64.0,21.38,0,0.0,1.0,57,56.386856
8131,4073719-08-R-20230710.jpg,0,158.4,64.0,25.51,0,0.0,1.0,79,69.473015
8132,7096147-02-R-20220816.jpg,0,164.7,61.3,22.60,0,0.0,0.0,50,45.289669
8133,7064104-06-L-20230508.jpg,0,146.3,61.5,28.73,0,0.0,0.0,64,62.306839

delete stroke = ***

In [40]:
merged_df = merged_df[merged_df['Event'] != '***']
merged_df = merged_df.reset_index(drop=True)

In [43]:
merged_df

,病歷號,抽菸,身高,體重,BMI,Event,高血壓,血脂異常,真實年齡,預測結果
0,4385815-02-L-20170802.jpg,0,149.0,71.0,31.98,0,1.0,1.0,64,57.276569
1,7093981-05-L-20200804.jpg,0,155.0,75.0,31.22,0,1.0,1.0,48,47.467751
2,4940688-05-R-20230201.jpg,0,167.7,93.3,33.18,0,0.0,0.0,60,57.765377
3,2310298-05-L-20220708.jpg,0,162.1,69.5,26.45,0,0.0,0.0,59,63.910080
4,4540756-03-R-20211102.jpg,0,166.2,78.7,28.49,0,0.0,1.0,70,55.230278
...,...,...,...,...,...,...,...,...,...,...
8115,4092882-01-R-20190103.jpg,0,150.9,55.8,24.51,0,0.0,1.0,64,61.213776
8116,4161150-04-L-20200131.jpg,1,173.0,64.0,21.38,0,0.0,1.0,57,56.386856
8117,4073719-08-R-20230710.jpg,0,158.4,64.0,25.51,0,0.0,1.0,79,69.473015
8118,7096147-02-R-20220816.jpg,0,164.7,61.3,22.60,0,0.0,0.0,50,45.289669
8119,7064104-06-L-20230508.jpg,0,146.3,61.5,28.73,0,0.0,0.0,64,62.306839

新增time欄位

In [44]:
# AC 欄位 = 中風日期 
# AD 欄位 = 心肌哽塞日期
    
# NaN欄位直接移除
# 值為1的會再去確認

# IF 沒有中風 , time = 20230616 - 第一張眼底鏡日期
# IF 中風          , time = 發病的日期-第一張眼底鏡日期

In [86]:
merged_df['病歷號'][1][-12:-4]

'20200804'

In [51]:
from datetime import datetime

In [93]:
merged_df['Time'] = ""

for i in range(len(merged_df['病歷號'])):
    merged_df['Event'][i] =  str(merged_df['Event'][i])

    if merged_df['Event'][i] != '0':

        if '(ICH)' in merged_df['Event'][i]:
            merged_df['Event'][i] = merged_df['Event'][i].replace('(ICH)', '')

        date = str(merged_df['Event'][i])
        date = datetime.strptime(date, '%Y%m%d')

        Imagedate = merged_df['病歷號'][i][-12:-4]
        Imagedate = datetime.strptime(Imagedate, '%Y%m%d')

        time = date - Imagedate
        time = abs(time.days)

        merged_df["Time"][i] = time
        
    else:

        NoStrokeDate = '20230616'
        NoStrokeDate = datetime.strptime(NoStrokeDate, '%Y%m%d')

        Imagedate = merged_df['病歷號'][i][-12:-4]
        Imagedate = datetime.strptime(Imagedate, '%Y%m%d')

        time = NoStrokeDate - Imagedate
        time = abs(time.days)
        merged_df["Time"][i] = time

/home/john/anaconda3/envs/retfound/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/john/anaconda3/envs/retfound/lib/python3.7/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/john/anaconda3/envs/retfound/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [94]:
merged_df

,病歷號,抽菸,身高,體重,BMI,Event,高血壓,血脂異常,真實年齡,預測結果,Time
0,4385815-02-L-20170802.jpg,0,149.0,71.0,31.98,0,1.0,1.0,64,57.276569,2144
1,7093981-05-L-20200804.jpg,0,155.0,75.0,31.22,0,1.0,1.0,48,47.467751,1046
2,4940688-05-R-20230201.jpg,0,167.7,93.3,33.18,0,0.0,0.0,60,57.765377,135
3,2310298-05-L-20220708.jpg,0,162.1,69.5,26.45,0,0.0,0.0,59,63.910080,343
4,4540756-03-R-20211102.jpg,0,166.2,78.7,28.49,0,0.0,1.0,70,55.230278,591
...,...,...,...,...,...,...,...,...,...,...,...
8115,4092882-01-R-20190103.jpg,0,150.9,55.8,24.51,0,0.0,1.0,64,61.213776,1625
8116,4161150-04-L-20200131.jpg,1,173.0,64.0,21.38,0,0.0,1.0,57,56.386856,1232
8117,4073719-08-R-20230710.jpg,0,158.4,64.0,25.51,0,0.0,1.0,79,69.473015,24
8118,7096147-02-R-20220816.jpg,0,164.7,61.3,22.60,0,0.0,0.0,50,45.289669,304
8119,7064104-06-L-20230508.jpg,0,146.3,61.5,28.73,0,0.0,0.0,64,62.306839,39

In [95]:
merged_df.to_csv('/home/john/network/RETFound/RETFound_MAE-main/Fundus_deepsurv/Regression/deepsurv.csv',index=False)